### ISSUE TITLE
Allow firefox as a `--media-player` option

### ISSUE THREAD

**Issue by BenjuhminStewart** [stefur/lizzy#3]
When running a firefox media player and running `playerctl --list-all` the listener for firefox is always a new value. For example you may get `firefox.instance_1_57` and then the next time you open you get `firefox.instance_1_156` so you cant set the media play flag to the exact value you need to when you want to grab just firefox's audio. If there is a current way to do this please let me know that'd be awesome. Thank you for your creating this custom module though, it is awesome!

**Comment by BenjuhminStewart** [comment]
Nevermind. I fixed this by making the `exec` tag the following value:

`"exec": "player=$(playerctl --list-all | grep 'firefox.instance*') && ~/.cargo/bin/lizzy --format '{{title}} - {{artist}}' --mediaplayer $player --autotoggle"`

**Comment by BenjuhminStewart** [comment]
Upon closing and reopening a firefox instance you have to reload your waybar instance in order to update the player variable containing the firefox instance value. Is there a way to do this without refreshing?

**Comment by stefur** [comment]
I also bumped into this issue a while back, but never got around to it. Perhaps a simple implementation of globbing could be enough in this case (and hopefully any similar cases). 
I'm thinking something that would allow for example `lizzy --mediaplayer firefox*` to catch any mediaplayers with `firefox` as the prefix. I'll look into it.

Glad to hear you enjoy the module!

**Comment by stefur** [comment]
Ok, I think I got it to work as expected. Check out 3d4633b and let me know!

**Comment by BenjuhminStewart** [comment]
That works. Great job! Also thank you for fixing it so quickly!

**Comment by stefur** [comment]
Nice!
I completely forgot about clearing the output after the window (or tab) is closed. Pushed another quick fix for now. :)

**Comment by BenjuhminStewart** [comment]
All works as expected now. Great Job!
